mode = "dark"
accent = "#D9AD7A"
selection = "#554637"
selection_foreground = "#F6EDDF"
selection_background = "#554637"
muted = "#C3B5A3"
background = "#2E2926"
dark_background = "#252220"
darker_background = "#1C1B1A"
lighter_background = "#3A332E"
foreground = "#EADFCF"
dark_foreground = "#C3B5A3"
light_foreground = "#DEC8AB"
bright_foreground = "#F6EDDF"
hyprland_active_border = "#B99B78"
hyprland_inactive_border = "#65594C"
red = "#EADFCF"
green = "#D9AD7A"
yellow = "#DEC8AB"
orange = "#DEC8AB"
blue = "#D9AD7A"
magenta = "#EADFCF"
cyan = "#C3B5A3"
brown = "#C3B5A3"
bright_red = "#F6EDDF"
bright_green = "#EADFCF"
bright_yellow = "#F6EDDF"
bright_blue = "#DEC8AB"
bright_magenta = "#EADFCF"
bright_cyan = "#D9AD7A"
