[bar]
background = "#3A332E"
background-alpha = 0.0
text = "#EADFCF"
active = "#D9AD7A"
scale-with-font = true
size-horizontal = 26
size-vertical = 28

[hyprland]
active-border = "#B99B78"
active-border-foreground = "#B99B78"

[controls]
normal-color = "foreground"
normal-fill-alpha = 0.04
normal-border = "foreground"
normal-border-width = 1
normal-border-alpha = 0.4
hover-cursor-color = "foreground"
hover-cursor-fill-alpha = 0.08
hover-cursor-border = "foreground"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.25
focus-color = "foreground"
focus-fill-alpha = 0.08
focus-border = "foreground"
focus-border-width = 1
focus-border-alpha = 0.65
selected-color = "foreground"
selected-fill-alpha = 0.18
selected-border = "foreground"
selected-border-width = 0
selected-border-alpha = 1.0
pressed-fill-alpha = 0.22
selection-fill-alpha = 0.35

[spacing]
scale = 1.0
scale-with-font = true

[font]
base-size = 12

[popups]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
border = "#65594C"
border-alpha = 1.0
border-width = 1

[tooltip]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
border = "#65594C"
border-alpha = 1.0

[notifications]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
border = "#65594C"
border-alpha = 1.0
border-width = 1
countdown = "#D9AD7A"

[launcher]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
border = "#65594C"
border-alpha = 1.0
scrim = "#1C1B1A"
scrim-alpha = 0.35
selected-background = "#554637"
selected-background-alpha = 1.0
selected-text = "#F6EDDF"
selected-border = "foreground"
selected-border-alpha = 0.35

[menu]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
border = "#65594C"
border-alpha = 1.0
scrim = "#1C1B1A"
scrim-alpha = 0.35
selected-background = "#554637"
selected-background-alpha = 1.0
selected-text = "#F6EDDF"
selected-border = "foreground"
selected-border-alpha = 0.35

[polkit]
background = "#3A332E"
background-alpha = 0.88
text = "#EADFCF"
text-error = "#E2BE94"
border = "hyprland.active-border"
border-error = "#E2BE94"
border-alpha = 1.0
scrim = "#1C1B1A"
scrim-alpha = 0.5
accent = "#D9AD7A"

[lock]
background = "#2E2926"
background-alpha = 0.88
text = "#EADFCF"
placeholder = "#C3B5A3"
text-error = "#E2BE94"
border = "#65594C"
border-active = "#D9AD7A"
border-error = "#E2BE94"
border-alpha = 1.0
selection = "#D9AD7A"
selection-alpha = 0.15

[image-picker]
scrim = "#1C1B1A"
scrim-alpha = 0.5
text = "#EADFCF"
selected-border = "foreground"
selected-border-alpha = 1.0
unselected-border = "foreground"
unselected-border-alpha = 0.28
